codecov:
  branch: master

coverage:
  precision: 2
  round: down
  range: "60...100"

  notify:
    slack:
      default:
        url: secret:8YqG1jGg5hYuzRw1A/VodGgOKKq8fDBfZSbdSwjgEYbcLljr1jbPLl4ZSLFlS1yp9UwM6rmyY3kx6QWGnEb3PVenM/5mUPt2RzPr63LjymMZgXYji7B0DsrQG104LQb8BdepIfHKM++D6V7YpT4TEd057M9NwK/iNabQV7epenI=
        threshold: 1
        branches: *
        attachments: "sunburst, diff"

  status:
    project:
      default:
        target: auto
        threshold: 1
        branches: *

    patch:
      default:
        target: auto
        branches: *

    changes:
      default:
        branches: *

  ignore:
    - test/.*
    - node_modules/.*
    - coverage/.*
    - docs/.*
    - resources/.*

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  branches: null
  behavior: default
